services:
  app:
    image: ghcr.io/basketikun/chatgpt2api:latest
    container_name: chatgpt2api
    restart: unless-stopped
    ports:
      - "3222:80"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json:ro
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G
    networks:
      - chatgpt2api
      - apinetwork
      
networks:
  chatgpt2api:
    name: chatgpt2api
  apinetwork:
    name: apinetwork
