services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatgpt2api:local
    container_name: chatgpt2api-local
    # image: ghcr.io/basketikun/chatgpt2api:latest
    ## container_name: chatgpt2api
    ports:
      - "3222:80"
    volumes:
      - chatgpt2api-data:/app/data
      - ./config.json:/app/config.json
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G
    networks:
      - chatgpt2api
      - apinetwork

volumes:
  chatgpt2api-data:
  
networks:
  chatgpt2api:
    name: chatgpt2api
  apinetwork:
    name: apinetwork
